// module.exports = {
//   masterSidebar: [
//     "home",
//     {
//       type: "category",
//       label: "Introduction",
//       collapsed: true,
//       items: [
//         "what-is-a-validator",
//         "what-is-an-rpc-node",
//         "faq",
//         "backwards-compatibility",
//       ],
//     },
//     {
//       type: "category",
//       label: "Nexis dApps",
//       collapsed: true,
//       items: [
//         {
//           type: "category",
//           label: "Nexis Bridge",
//           collapsed: true,
//           items: [
//             "nexis-bridge-overview",
//           ],
//         },
//         {
//           type: "category",
//           label: "Nexis Web Wallet",
//           collapsed: true,
//           items: [
//             "ns-overview",
//             "ns-glossary",
//           ],
//         },
//         {
//           type: "category",
//           label: "Nexis Swap",
//           collapsed: true,
//           items: [
//             "ns-overview",
//             "nexis-swap-smart-contracts",
//             "ns-glossary",
//           ],
//         },
//         {
//           type: "category",
//           label: "Nexis Names Service",
//           collapsed: true,
//           items: [
//             "graph-node",
//             "subgraph"
//           ],
//         },
//         {
//           type: "category",
//           label: "Nexis Safe",
//           collapsed: true,
//           items: [
//             "graph-node",
//             "subgraph"
//           ],
//         },
//         {
//           type: "category",
//           label: "Nexis Testnet Faucet",
//           collapsed: true,
//           items: [
//             "graph-node",
//             "subgraph"
//           ],
//         },
//       ],
//     },
//     {
//       type: "category",
//       label: "Command Line Tools",
//       // collapsed: true,
//       items: [
//         {
//           type: "autogenerated",
//           dirName: "cli",
//         },
//       ],
//     },
//     {
//       type: "category",
//       label: "Architecture",
//       // collapsed: true,
//       items: [
//         "architecture",
//         {
//           type: "category",
//           label: "Clusters",
//           // collapsed: true,
//           items: [
//             {
//               type: "autogenerated",
//               dirName: "clusters",
//             },
//           ],
//         },
//         {
//           type: "category",
//           label: "Consensus",
//           // collapsed: true,
//           items: [
//             {
//               type: "autogenerated",
//               dirName: "consensus",
//             },
//           ],
//         },
//         {
//           type: "category",
//           label: "Runtime",
//           // collapsed: true,
//           items: [
//             {
//               type: "autogenerated",
//               dirName: "runtime",
//             },
//           ],
//         },
//         {
//           type: "category",
//           label: "Validators",
//           // collapsed: true,
//           items: [
//             {
//               type: "autogenerated",
//               dirName: "validator",
//             },
//           ],
//         },
//       ],
//     },
//     {
//       type: "category",
//       label: "Operating a Validator",
//       // collapsed: true,
//       items: [
//         {
//           type: "autogenerated",
//           dirName: "operations",
//         },
//       ],
//     },
//   ],
//   proposalsSidebar: [
//     {
//       type: "category",
//       label: "System Design Proposals",
//       collapsed: true,
//       items: [
//         "proposals",
//         {
//           type: "category",
//           label: "Accepted Proposals",
//           collapsed: true,
//           link: {
//             type: "doc",
//             id: "proposals/accepted-design-proposals",
//           },
//           items: [
//             {
//               type: "autogenerated",
//               dirName: "proposals",
//             },
//           ],
//         },
//         {
//           type: "category",
//           label: "Implemented Proposals",
//           collapsed: true,
//           link: {
//             type: "doc",
//             id: "implemented-proposals/index",
//           },
//           items: [
//             {
//               type: "autogenerated",
//               dirName: "implemented-proposals",
//             },
//           ],
//         },
//       ],
//     },
//   ],
// };
module.exports = {
  masterSidebar: [
    "home",
    {
      type:"category",
      label:"Infrastructure",
      collapsed:true,
      items:[
        'architecture',
        'clusters'
      ]
    },
    {
      type:"category",
      label:"Products",
      collapsed:true,
      items:[
        {
          type: "category",
          label: "Wallets",
          collapsed: true,
          items: [
            'wallet',
            {
              type: "category",
              label: "Web Wallets",
              collapsed: true,
              items: [
                'web-wallet',
                'safe-web-wallet'
              ],
            },
            {
              type: "category",
              label: "Wallet Extensions",
              collapsed: true,
              items: [
                'metamask',
              ],
            }
          ],
        },
        {
          type: "category",
          label: "Bridges",
          collapsed: true,
          items: [
            'bridges',
           'bridge'
          ],
        },
        {
          type: "category",
          label: "DEXs",
          collapsed: true,
          items: [
            'dexs',
            'swap'
          ],
        },
        {
          type: "category",
          label: "Name Services",
          collapsed: true,
          items: [
            'names',
            'nameservice'
          ],
        },
        {
          type: "category",
          label: "Faucets",
          collapsed: true,
          items: [
            'faucets',
            'faucet'
          ],
        },
      ]
    },
   
  ],
};
